# Auto-generated by Helios — do not edit manually.
# Regenerate by re-downloading the stack from https://helios.app
from __future__ import annotations

import os
from typing import Any

import httpx

_BASE_URL = os.getenv("API_URL", "http://localhost:8080")


class HeliosClient:
    def __init__(self, base_url: str = _BASE_URL, token: str | None = None) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._http = httpx.Client(base_url=self._base_url)

    def with_token(self, token: str) -> "HeliosClient":
        self._token = token
        return self

    def _request(self, method: str, path: str, **kwargs: Any) -> httpx.Response:
        res = self._http.request(method, path, **kwargs)
        res.raise_for_status()
        return res

    def get_a_user_by_id(self, self, id: str, **kwargs: Any) -> httpx.Response:
        """GET /users/:id — Get a user by ID"""
        if self._token:
            kwargs.setdefault("headers", {})["Authorization"] = f"Bearer {self._token}"
        return self._request("GET", f"/users/{id}", **kwargs)

    def create_a_new_user(self, self, body: dict | None = None, **kwargs: Any) -> httpx.Response:
        """POST /users — Create a new user"""
        kwargs.setdefault("json", body or {})
        return self._request("POST", "/users", **kwargs)

    def login_and_issue_jwt(self, self, body: dict | None = None, **kwargs: Any) -> httpx.Response:
        """POST /auth/login — Login and issue JWT"""
        kwargs.setdefault("json", body or {})
        return self._request("POST", "/auth/login", **kwargs)

    def liveness_probe(self, self, **kwargs: Any) -> httpx.Response:
        """GET /health — Liveness probe"""
        return self._request("GET", "/health", **kwargs)

    def __enter__(self) -> "HeliosClient":
        return self

    def __exit__(self, *_: object) -> None:
        self._http.close()


client = HeliosClient()
