// Auto-generated by Helios — do not edit manually.
// Regenerate by re-downloading the stack from https://helios.app

const BASE_URL = process.env.API_URL ?? "http://localhost:8080";

export class HeliosClient {
  private baseUrl: string;
  private token: string | null;

  constructor(baseUrl = BASE_URL, token: string | null = null) {
    this.baseUrl = baseUrl;
    this.token = token;
  }

  withToken(token: string): this {
    this.token = token;
    return this;
  }

  private async request(path: string, init: RequestInit = {}): Promise<Response> {
    const res = await fetch(this.baseUrl + path, init);
    if (!res.ok) {
      const text = await res.text().catch(() => "");
      throw new Error(`${init.method ?? "GET"} ${path} failed (${res.status}): ${text}`);
    }
    return res;
  }

  async getAUserByID(params: { id: string }, options?: RequestInit) {
    return this.request(`/users/${params.id}`, {
      method: "GET",
      headers: { "Content-Type": "application/json",
    ...(token ? { Authorization: `Bearer ${token}` } : {}), },
      ...options,
    });
  },

  async createANewUser(body: Record<string, unknown>, options?: RequestInit) {
    return this.request("/users", {
      method: "POST",
      headers: { "Content-Type": "application/json", },
    body: JSON.stringify(body),
      ...options,
    });
  },

  async loginAndIssueJWT(body: Record<string, unknown>, options?: RequestInit) {
    return this.request("/auth/login", {
      method: "POST",
      headers: { "Content-Type": "application/json", },
    body: JSON.stringify(body),
      ...options,
    });
  },

  async livenessProbe(options?: RequestInit) {
    return this.request("/health", {
      method: "GET",
      headers: { "Content-Type": "application/json", },
      ...options,
    });
  }
}

export const client = new HeliosClient();
